### ISSUE TITLE
CONTRIBUTING.md issues part is incomplete

### ISSUE THREAD

**Issue by daxtery** [alexdqmf/wwa#15]
_Originally posted by @suppergerrie2 in https://github.com/alexdqmf/wwa/pull/14/threads/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMzEzNTU1NTY2/resolve_

**Comment by suppergerrie2** [comment]
Maybe explain how to do this or do you think that is self explanatory?

**Comment by daxtery** [comment]
I think it's intuitive enough, no?
